#pragma once
#include <bits/stdc++.h>
using namespace std;

enum STATE {
    start,
    normal,
    final,
    dead,
};

class NFA {
public:
    struct node {
        STATE state = STATE::normal;
        map<char, vector<int>> next;
        set<pair<int, string>> messages;
    };

    vector<node> v;

    NFA() {
        v.resize(1);
        v[0].state = STATE::start;
    }

    int add_state(STATE state) {
        int num = v.size();
        v.push_back(node());
        v[num].state = state;
        return num;
    }

    int add_state(node state) {
        v.push_back(state);
        return v.size() - 1;
    }

    void change_state(int i, STATE new_state) {
        v[i].state = new_state;
    }

    void shift(int sh) {
        for (auto &[state, nxt, messages] : v) {
            for (auto &[f, s] : nxt) {
                for (auto &it : s) {
                    it += sh;
                }
            }
        }
    }

    vector<int> get_final_states() {
        vector<int> ret;
        for (int i = 0; i < v.size(); ++i) {
            if (v[i].state == STATE::final) {
                ret.push_back(i);
            }
        }
        return ret;
    }

    void add_edge(int from, int to, char c) {
        v[from].next[c].push_back(to);
    }

    void display() {
        for (int i = 0; i < v.size(); ++i) {
            if (v[i].messages.size()) {
                cout << "\"" << v[i].messages.begin()->second << "\"";
            }
            if (v[i].state == STATE::start) cout << "start" << " " << i << "{";
            if (v[i].state == STATE::normal) cout << "normal" << " " << i << "{";
            if (v[i].state == STATE::final) cout << "final" << " " << i << "{";
            for (auto &[ch, nxt] : v[i].next) {
                cout << "\'" << ch << "\'" << ":";
                for (auto x : nxt) {
                    cout << x << ",";
                }
                cout << "| ";
            }
            cout << "}" << '\n';
        }
    }

    // compressRanges was generated by chatgpt
    void compressRanges(string &input) {
        auto trim = [](string s) {
            size_t l = 0, r = s.size();
            while (l < r && isspace((unsigned char)s[l]))
                l++;
            while (r > l && isspace((unsigned char)s[r - 1]))
                r--;
            return s.substr(l, r - l);
        };

        auto sameGroup = [](char a, char b) {
            return (islower((unsigned char)a) && islower((unsigned char)b)) ||
                   (isupper((unsigned char)a) && isupper((unsigned char)b)) ||
                   (isdigit((unsigned char)a) && isdigit((unsigned char)b));
        };

        vector<char> chars;
        stringstream ss(input);
        string token;

        while (getline(ss, token, ',')) {
            token = trim(token);
            if (token.size() == 1)
                chars.push_back(token[0]);
        }

        if (chars.empty()) return;

        string result;
        for (size_t i = 0; i < chars.size();) {
            char start = chars[i];
            char end = chars[i];
            size_t j = i;

            while (j + 1 < chars.size() &&
                   sameGroup(chars[j], chars[j + 1]) &&
                   chars[j + 1] == chars[j] + 1) {
                end = chars[j + 1];
                j++;
            }

            if (!result.empty()) result += ", ";

            if (start == end)
                result += start;
            else
                result += "[" + string(1, start) + "-" + string(1, end) + "]";

            i = j + 1;
        }

        input = result;
    }

    // minimize was generated by chatgpt
    void minimize() {
        const char EPS = '_';

        if (v.empty()) return;

        vector<node> old = v;

        // The combined automaton is assumed to have state 0 as the global start.
        // If there are lambda edges from state 0, each target is treated as one
        // independent regex branch. Otherwise, the whole automaton is treated as one branch.
        vector<int> roots;
        if (old[0].next.count(EPS) && !old[0].next[EPS].empty()) {
            roots = old[0].next[EPS];
        }
        else {
            roots = {0};
        }

        vector<node> rebuilt(1);
        rebuilt[0].state = STATE::start;

        for (int root : roots) {
            // ------------------------------------------------------------
            // 1) Collect the states of this branch only.
            //    We intentionally do not walk back through global state 0,
            //    so branches stay separated.
            // ------------------------------------------------------------
            set<int> branch_states;
            queue<int> qq;
            branch_states.insert(root);
            qq.push(root);

            while (!qq.empty()) {
                int u = qq.front();
                qq.pop();

                for (auto &[ch, nxts] : old[u].next) {
                    for (int to : nxts) {
                        if (to == 0 && root != 0) continue; // don't cross through global combiner
                        if (!branch_states.count(to)) {
                            branch_states.insert(to);
                            qq.push(to);
                        }
                    }
                }
            }

            // Alphabet of this branch (excluding epsilon)
            vector<char> alphabet;
            {
                set<char> alpha_set;
                for (int s : branch_states) {
                    for (auto &[ch, nxts] : old[s].next) {
                        if (ch != EPS) alpha_set.insert(ch);
                    }
                }
                alphabet.assign(alpha_set.begin(), alpha_set.end());
            }

            // ------------------------------------------------------------
            // 2) Local lambdas used only inside this function
            // ------------------------------------------------------------
            auto epsilon_closure = [&](const vector<int> &start_states) {
                set<int> closure;
                stack<int> st;

                for (int s : start_states) {
                    if (branch_states.count(s) && !closure.count(s)) {
                        closure.insert(s);
                        st.push(s);
                    }
                }

                while (!st.empty()) {
                    int u = st.top();
                    st.pop();

                    auto it = old[u].next.find(EPS);
                    if (it == old[u].next.end()) continue;

                    for (int to : it->second) {
                        if (!branch_states.count(to)) continue;
                        if (!closure.count(to)) {
                            closure.insert(to);
                            st.push(to);
                        }
                    }
                }

                return vector<int>(closure.begin(), closure.end());
            };

            auto move_on_char = [&](const vector<int> &subset, char c) {
                set<int> dest;
                for (int s : subset) {
                    auto it = old[s].next.find(c);
                    if (it == old[s].next.end()) continue;
                    for (int to : it->second) {
                        if (branch_states.count(to)) dest.insert(to);
                    }
                }
                vector<int> moved(dest.begin(), dest.end());
                return epsilon_closure(moved);
            };

            // ------------------------------------------------------------
            // 3) Subset construction: branch NFA -> DFA
            // ------------------------------------------------------------
            vector<vector<int>> dfa_states;
            map<vector<int>, int> dfa_id;
            vector<map<char, int>> dfa_trans;
            vector<bool> dfa_final;
            vector<set<pair<int, string>>> dfa_messages;

            auto register_subset = [&](const vector<int> &subset) {
                if (dfa_id.count(subset)) return dfa_id[subset];

                int id = (int)dfa_states.size();
                dfa_id[subset] = id;
                dfa_states.push_back(subset);
                dfa_trans.push_back({});
                dfa_final.push_back(false);
                dfa_messages.push_back({});

                for (int s : subset) {
                    if (old[s].state == STATE::final) {
                        dfa_final[id] = true;
                        dfa_messages[id].insert(old[s].messages.begin(), old[s].messages.end());
                    }
                }

                return id;
            };

            vector<int> start_subset = epsilon_closure({root});
            int dfa_start = register_subset(start_subset);

            queue<int> dq;
            dq.push(dfa_start);

            vector<int> vis_dfa(1, 0);
            vis_dfa[dfa_start] = 1;

            while (!dq.empty()) {
                int cur = dq.front();
                dq.pop();

                for (char c : alphabet) {
                    vector<int> nxt_subset = move_on_char(dfa_states[cur], c);
                    if (nxt_subset.empty()) continue;

                    int nxt_id = register_subset(nxt_subset);
                    dfa_trans[cur][c] = nxt_id;

                    if ((int)vis_dfa.size() < (int)dfa_states.size())
                        vis_dfa.resize(dfa_states.size(), 0);

                    if (!vis_dfa[nxt_id]) {
                        vis_dfa[nxt_id] = 1;
                        dq.push(nxt_id);
                    }
                }
            }

            int dfa_n = (int)dfa_states.size();
            if (dfa_n == 0) continue;

            // ------------------------------------------------------------
            // 4) Minimize the DFA by partition refinement
            //    Final states are initially separated by their message sets.
            // ------------------------------------------------------------
            vector<vector<int>> parts;
            vector<int> nonfinal_part;
            map<set<pair<int, string>>, vector<int>> final_groups;

            for (int i = 0; i < dfa_n; ++i) {
                if (dfa_final[i])
                    final_groups[dfa_messages[i]].push_back(i);
                else
                    nonfinal_part.push_back(i);
            }

            if (!nonfinal_part.empty()) parts.push_back(nonfinal_part);
            for (auto &[msgset, states] : final_groups) {
                if (!states.empty()) parts.push_back(states);
            }

            vector<int> cls(dfa_n, -1);
            auto rebuild_classes = [&]() {
                fill(cls.begin(), cls.end(), -1);
                for (int i = 0; i < (int)parts.size(); ++i) {
                    for (int s : parts[i])
                        cls[s] = i;
                }
            };

            rebuild_classes();

            bool changed = true;
            while (changed) {
                changed = false;
                vector<vector<int>> new_parts;

                for (auto &part : parts) {
                    map<vector<int>, vector<int>> buckets;

                    for (int s : part) {
                        vector<int> sig;
                        for (char c : alphabet) {
                            auto it = dfa_trans[s].find(c);
                            int to_class = -1;
                            if (it != dfa_trans[s].end()) {
                                to_class = cls[it->second];
                            }
                            sig.push_back(to_class);
                        }
                        buckets[sig].push_back(s);
                    }

                    if (buckets.size() == 1) {
                        new_parts.push_back(part);
                    }
                    else {
                        changed = true;
                        for (auto &[sig, group] : buckets) {
                            new_parts.push_back(group);
                        }
                    }
                }

                parts = new_parts;
                rebuild_classes();
            }

            // ------------------------------------------------------------
            // 5) Build minimized branch back into your NFA structure.
            //    We keep the global start state and preserve one lambda edge
            //    from it to this minimized branch.
            // ------------------------------------------------------------
            int base = (int)rebuilt.size();
            vector<int> part_to_new(parts.size(), -1);

            for (int i = 0; i < (int)parts.size(); ++i) {
                int rep = parts[i][0];

                node nd;
                nd.state = dfa_final[rep] ? STATE::final : STATE::normal;
                nd.messages = dfa_messages[rep];

                rebuilt.push_back(nd);
                part_to_new[i] = base + i;
            }

            // transitions between minimized states
            for (int i = 0; i < (int)parts.size(); ++i) {
                int rep = parts[i][0];
                int from = part_to_new[i];

                for (char c : alphabet) {
                    auto it = dfa_trans[rep].find(c);
                    if (it == dfa_trans[rep].end()) continue;

                    int to_part = cls[it->second];
                    int to = part_to_new[to_part];
                    rebuilt[from].next[c].push_back(to);
                }
            }

            // preserve the lambda edge that combines this regex with the global start
            rebuilt[0].next[EPS].push_back(part_to_new[cls[dfa_start]]);
        }

        v = rebuilt;
    }

    string generate_graph_code() {
        minimize();
        ostringstream cout;
        cout << "digraph G {\n_[style = invisible];\nrectangle_label [shape=rectangle, label=\"#: represents any character except [a-z][A-Z][0-9]\\\"(){}+-/*:=<;,\"];\n0[style = filled];\n_ -> 0;\n";
        int n = v.size();
        vector<vector<string>> a(n, vector<string>(n));

        for (int i = 0; i < v.size(); ++i) {
            if (v[i].state == STATE::final) {
                auto msg = v[i].messages.begin()->second;
                cout << i << "[shape=doublecircle" << ",label=\"" << i << ": " << msg << "\"];\n";
            }
            for (auto &[ch, it] : v[i].next) {
                for (auto nxt : it) {
                    a[i][nxt] += string((ch == '\\' or ch == '\"') ? "\\" : "") + (ch == '_' ? "lambda" : string(1, ch)) + ',';
                }
                // cout << i << " -> " << nxt << " [label=\"" << ((ch == '\\' or ch == '\"') ? "\\" : "") << ch << "\"];";
                // cout << '\n';
            }
        }

        for (int i = 0; i < n; ++i) {
            for (int j = 0; j < n; ++j) {
                if (a[i][j].size()) {
                    a[i][j].pop_back();
                    compressRanges(a[i][j]);
                    cout << i << " -> " << j << " [label=\"" << a[i][j] << "\"];" << '\n';
                }
            }
        }

        cout << "\n}";
        return cout.str();
    }
};
